### ISSUE TITLE
Recommendations for saving Snakefile and config/cluster files do they don't get overwritten with pulls

### ISSUE THREAD

**Issue by janaobsteter** [HighlanderLab/tree_seq_pipeline#48]

**Comment by hannesbecher** [comment]
Config files need not be hard coded into the Snakefile. They can be specified on the commandline with `--configfile`, see https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html. So, everybody can make their specific config files and leave them untracked.

Happy to add this to the readme.

**Comment by hannesbecher** [comment]
Also, I think it would be good to have the tsinfer params in a config file rather than in a script file. I just opened #68 about this.

**Comment by hannesbecher** [comment]
Added recommendations to README.md in PR #69 . Everyone can set up their own config file and specify on the command line via `--configfile myFile.yaml`. `beetest.yaml` can be used as a template.
