### ISSUE TITLE
Change all paths to absolute

### ISSUE THREAD

**Issue by janaobsteter** [HighlanderLab/tree_seq_pipeline#52]
Have a `workdir` variable and use that instead of "../...."

**Comment by janaobsteter** [comment]
1. Add a `workdir` variable to Snakefile that reads the `workdir` from the config file
2. In all the rules, search for a path "../{Project}/..." and change it to "{workdir}/...."

Be careful to keep the commas and the brackets as they are

**Comment by hannesbecher** [comment]
Solved with PR #67  
The yaml key is `o_dir`, variable inside Snakelike file is `oDir`.
