### ISSUE TITLE
reproducible testing

### ISSUE THREAD

**Issue by hannesbecher** [HighlanderLab/tree_seq_pipeline#66]
I am still struggling with testing.

@janaobsteter @gmafrafortuna I would like to include the small bee test data set in the repo, would that be OK? Altenatively, this could be in a separate repo that's pulled in as a sub-module. Opinions?

**Comment by janaobsteter** [comment]
Yeah, sure, go for it! You can use files from that "Data" folder in `HighlanderLab/share/Snakemake/Data` that we use for testing. I vote for having it in the repo.

**Comment by gmafrafortuna** [comment]
I'm happy with that as well!

**Comment by hannesbecher** [comment]
Solved with PR #67
